Initial split into separate repo
embedded-graphics/simulator pull request #1
Opened 2020-11-03 10:19 UTC by jamwaffles

2020-11-04 18:49 UTC, rfuest requested changes
The `doc` and `examples` directories should be in this repo, but we can move them later.

2020-11-04 18:49 UTC, rfuest commented on Cargo.toml
> +    "convert_1bpp.sh",
```suggestion
    "/.circleci/",
    "/.github/",
    ".gitignore",
```

2020-11-04 18:49 UTC, rfuest commented on README.tpl
> +[![Build Status](https://circleci.com/gh/embedded-graphics/embedded-graphics/tree/master.svg?style=shield)](https://circleci.com/gh/embedded-graphics/embedded-graphics/tree/master)
This needs to be updated to use the simulator build status.

2020-11-05 15:02 UTC, rfuest requested changes
One small nit left...

2020-11-05 15:02 UTC, rfuest commented on CHANGELOG.md
> +[unreleased - `embedded-graphics` repository]: https://github.com/embedded-graphics/embedded-graphics/compare/embedded-graphics-simulator-v0.2.0...HEAD
```suggestion
[unreleased - `embedded-graphics` repository]: https://github.com/embedded-graphics/embedded-graphics/compare/embedded-graphics-simulator-v0.2.0...before-split
```

2020-11-05 15:12 UTC, jamwaffles commented
I was so close  *shakes fist

2020-11-05 15:13 UTC, rfuest approved these changes
Looks good now.

2020-11-05 15:20 UTC, merged