Add release docs
embedded-graphics/simulator pull request #35
Opened 2021-06-15 16:27 UTC by jamwaffles

Astute reviewers will recognise most of the e-g release steps in here, but they're plenty good enough to copy over ;)

2021-06-15 16:29 UTC, jamwaffles commented
When this PR is merged, it would be great if @rfuest could try releasing 0.3.1 to publish #34 and exercise the release docs.

2021-06-15 16:34 UTC, rfuest commented
> When this PR is merged, it would be great if @rfuest could try releasing 0.3.1 to publish #34 and exercise the release docs.

Good idea. I don't have time in the moment, but I'll try to find some time in the next few days.

We could also merge this after I've released `0.3.1`, so that we can tweak the docs if I encounter any problems.

2021-06-15 16:44 UTC, jamwaffles commented
> I don't have time in the moment, but I'll try to find some time in the next few days.

Awesome, let us know when you get round to it.

> We could also merge this after I've released 0.3.1, so that we can tweak the docs if I encounter any problems.

Also a good idea. If I could find it, I'd allow you to push to this branch but I can't find the setting...

2021-06-16 15:04 UTC, jamwaffles commented
By the way, I've added the e-g core team as allowed to push to `master` for tinytga, tinybmp, simulator and e-g itself so when you release, hopefully the Git tags are pushed by `cargo-release`. I'd suggest attempting to release one of the `tiny*` crates first to figure out any teething problems.

2021-06-19 16:37 UTC, rfuest requested changes

2021-06-19 16:37 UTC, rfuest commented on doc/releasing.md
> +  Where `<level>` is `major`, `minor`, `patch`, or a specific SemVer version number.
```suggestion
  cargo release --push-remote <push-remote> <level>
  ```

  Where `<level>` is `major`, `minor`, `patch`, or a specific SemVer version number. And where `<push-remote>` is the git remote for the upstream repository `embedded-graphics/simulator`.
```

2021-06-22 14:07 UTC, rfuest approved these changes
LGTM. The suggestion about the git remote will also need to be added to all other release docs.

2021-06-22 14:14 UTC, jamwaffles commented
Thanks! Yeah, I'll add that into the other ones now. Prepare for review groundhog day...

2021-06-22 14:14 UTC, merged