Update dependencies: image, base64, sdl2
embedded-graphics/simulator pull request #55
Opened 2024-07-11 20:19 UTC by sciguy16

Thank you for helping out with embedded-graphics-simulator development! Please:

- [x] Check that you've added passing tests and documentation
- [ ] ~~Add an example where applicable~~
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [x] Run `rustfmt` on the project
- [x] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

Hi, I noticed that the version of `image` this crate depends on in the published release is 0.23.4 (can be seen on the [crates.io page](https://crates.io/crates/embedded-graphics-simulator/0.6.0/dependencies) rather than the 0.24.7 promised by the changelog. In the meantime, of course, there's been another version out so I've bumped the 3 now outdated dependencies to their latest versions.

I've also fixed some clippy warnings - let me know if you'd prefer that commit to be moved to a separate PR or if it's okay bundled in with this one.

2024-07-11 20:24 UTC, sciguy16 commented
Ah, CI is failing because the `bitstream-io` transitive dependency of `image` has an MSRV of 1.79. Might have to back out the `image` update if we want it to build on 1.71

2024-07-12 00:39 UTC, rfuest requested changes
Good catch, I don't know how the release version did get out of sync with the repo, but it seems that the release on crates.io is based on d11431fef3deb4406fe6a226cb1a3bb782cbc418 and not the latest commit at that time.

> Ah, CI is failing because the bitstream-io transitive dependency of image has an MSRV of 1.79. Might have to back out the image update if we want it to build on 1.71

I wouldn't mind bumping the MSRV a bit, but I think we should at least support a couple of stable releases back if possible.

According to [this issue](https://github.com/image-rs/image/issues/2261) the bump in the MSRV is caused by the `ravif` feature, which we don't use. By changing the `image`  dependency we might be able to work around the issue:
```
image = { version = "0.25.1", default_features = false, features = ["png"] }
```

2024-07-12 00:39 UTC, rfuest commented on CHANGELOG.md
> +- **(breaking)** [#55](https://github.com/embedded-graphics/simulator/pull/49) Bump the following crate dependencies: `image` to 0.25.1, `base64` to 0.22.1, `sdl2` to 0.37.0
```suggestion
- **(breaking)** [#55](https://github.com/embedded-graphics/simulator/pull/55) Bump the following crate dependencies: `image` to 0.25.1, `base64` to 0.22.1, `sdl2` to 0.37.0
```

2024-07-12 09:11 UTC, sciguy16 commented
Good spot, I've turned off the default features on `image` and now the tests pass on 1.71

2024-07-12 14:21 UTC, rfuest approved these changes
LGTM

2024-07-12 14:22 UTC, merged